version: 2.3.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: AssemblyInfo.Common.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-CI'
dotnet_csproj:
  patch: true
  file: Common.props
  version: '{version}'
  package_version: '{version}'
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
test_script:
- cmd: >-
    cd UnicodeInformation.Tests

    dotnet xunit
artifacts:
- path: UnicodeCharacterInspector\bin\Release
  name: UnicodeCharacterInspector
- path: UnicodeInformation\bin\Release\UnicodeInformation.*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  api_key:
    secure: S1uTeXbjD8eLun90hsjHjyf2TpjxOWS9YW7Z2Xu7Cg/sV5ogRm7OAr9P7E5lhueE
  skip_symbols: true
  on:
    branch: master